"""init3

Revision ID: 512ef01f1b9a
Revises: 840690aa2e2d
Create Date: 2024-10-18 09:49:25.908080+04:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '512ef01f1b9a'
down_revision: Union[str, None] = '840690aa2e2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('receiver_id', sa.Integer(), nullable=False))
    op.drop_constraint('messages_reseiver_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['receiver_id'], ['id'], ondelete='CASCADE')
    op.drop_column('messages', 'reseiver_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('reseiver_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_reseiver_id_fkey', 'messages', 'users', ['reseiver_id'], ['id'], ondelete='CASCADE')
    op.drop_column('messages', 'receiver_id')
    # ### end Alembic commands ###
