"""remove_avatar_link

Revision ID: af60c141fbe9
Revises: ac0fd9515be7
Create Date: 2024-09-20 13:46:12.485742+04:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af60c141fbe9'
down_revision: Union[str, None] = 'ac0fd9515be7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'photo_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('photo_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
